import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Glide Data Grid Demo</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<p>
					<Link href={'/text-styling'}>Text Styling</Link>
				</p>
				<p>
					<Link href={'/simple-grid'}>Simple Grid</Link>
				</p>
			</main>
		</>
	);
}
